"""Dijkstra shortest paths over sparse 3D voxel sets.

A sparse analogue of `dijkstra3d <https://github.com/seung-lab/dijkstra3d>`_:
the same implicit-grid walk (neighbours generated by coordinate offset, no
adjacency list ever materialized), but the dense bbox-sized lookup array is
replaced by a sparse ``coordinate -> compact index`` map. All working memory
is ``O(N)`` in the number of voxels, independent of the bounding-box volume.

Voxels are given as an ``(N, 3)`` integer coordinate array; all per-voxel
inputs and outputs (``node_cost``, ``free_mask``, ``dist``, ``pred``,
``labels``) are 1-D arrays aligned with the rows of ``voxels``.
"""

from __future__ import annotations

from typing import Optional, Tuple, Union

import numpy as np
import numpy.typing as npt

from . import _native

__all__ = [
    "dijkstra_field",
    "path",
    "connected_components",
    "index_of",
    "__version__",
]

__version__ = "0.1.0"

_COST_MODES = ("vertex", "additive", "geometric")
_CONNECTIVITIES = (6, 18, 26)
_INDEX_KINDS = ("sorted", "hash")


def _as_voxels(voxels: npt.ArrayLike) -> np.ndarray:
    """Coerce to a C-contiguous (N, 3) int32 array, rejecting lossy casts."""
    arr = np.asarray(voxels)
    if arr.ndim != 2 or arr.shape[1] != 3:
        raise ValueError(f"voxels must have shape (N, 3), got {arr.shape}")
    if not np.issubdtype(arr.dtype, np.integer):
        raise ValueError(f"voxels must be an integer array, got dtype {arr.dtype}")
    if arr.dtype != np.int32:
        if arr.size and (arr.min() < np.iinfo(np.int32).min or arr.max() > np.iinfo(np.int32).max):
            raise ValueError("voxel coordinates exceed the int32 range")
        arr = arr.astype(np.int32)
    return np.ascontiguousarray(arr)


def _as_sources(sources: npt.ArrayLike, n: int) -> np.ndarray:
    arr = np.atleast_1d(np.asarray(sources))
    if arr.ndim != 1:
        raise ValueError(f"sources must be a 1-D array of row indices, got shape {arr.shape}")
    if arr.size and not np.issubdtype(arr.dtype, np.integer):
        raise ValueError(f"sources must be integer row indices into voxels, got dtype {arr.dtype}")
    arr = np.ascontiguousarray(arr, dtype=np.int64)
    if arr.size and (arr.min() < 0 or arr.max() >= n):
        bad = arr[(arr < 0) | (arr >= n)][0]
        raise ValueError(f"source index {bad} out of range for {n} voxels")
    return arr


def _as_node_cost(node_cost: npt.ArrayLike, n: int) -> np.ndarray:
    arr = np.ascontiguousarray(node_cost, dtype=np.float32)
    if arr.shape != (n,):
        raise ValueError(f"node_cost must have shape (N,) = ({n},), got {arr.shape}")
    if arr.size and (not np.all(np.isfinite(arr)) or arr.min() < 0):
        raise ValueError(
            "node_cost must be finite and non-negative "
            "(negative costs violate the Dijkstra invariant)"
        )
    return arr


def dijkstra_field(
    voxels: npt.ArrayLike,
    sources: npt.ArrayLike,
    *,
    node_cost: Optional[npt.ArrayLike] = None,
    connectivity: int = 26,
    anisotropy: Tuple[float, float, float] = (1.0, 1.0, 1.0),
    cost_mode: str = "vertex",
    free_mask: Optional[npt.ArrayLike] = None,
    free_eps: float = 1e-6,
    min_only: bool = True,
    index_kind: str = "hash",
) -> Tuple[np.ndarray, np.ndarray]:
    """Multi-source Dijkstra distance + predecessor field over sparse voxels.

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates (unsorted is fine, duplicates
        are rejected). Any integer dtype in int32 range.
    sources
        Row indices into ``voxels`` to start from (scalar or 1-D array).
        Use :func:`index_of` if you hold coordinates instead. May be empty,
        in which case every voxel is unreached.
    node_cost
        Optional ``(N,)`` per-voxel weight, ``float32`` (other dtypes are
        converted). Must be finite and non-negative. When ``None``, every
        edge costs just its geometric step length regardless of
        ``cost_mode``.
    connectivity
        6, 18 or 26 (face / face+edge / face+edge+corner neighbours).
    anisotropy
        Physical voxel spacing ``(wx, wy, wz)``. Step lengths are
        ``sqrt((dx*wx)^2 + (dy*wy)^2 + (dz*wz)^2)``, matching ``dijkstra3d``.
    cost_mode
        - ``"vertex"`` (default): ``cost = node_cost[nbr] * step_length`` —
          ``dijkstra3d``-compatible vertex weighting.
        - ``"additive"``: ``cost = step_length + node_cost[nbr]`` — geometric
          length plus a per-voxel penalty.
        - ``"geometric"``: ``cost = step_length`` — anisotropic geodesic
          distance; ``node_cost`` is ignored.
    free_mask
        Optional ``(N,)`` bool mask. Edges *into* masked voxels cost
        ``free_eps`` in total, so later paths can ride an already-selected
        node set for ~free before diverging (incremental path grafting).
    free_eps
        Strictly positive cost of edges into ``free_mask`` voxels.
    min_only
        With multiple sources: if True (default) return one field with the
        distance to the *nearest* source; if False run one Dijkstra per
        source and return ``(S, N)`` arrays (rows ordered like ``sources``),
        mirroring :func:`scipy.sparse.csgraph.dijkstra`.
    index_kind
        Spatial-index backend, ``"hash"`` (hash map, default — fastest in
        our benchmarks) or ``"sorted"`` (binary search over sorted keys,
        slightly lower memory). Identical results; performance knob only.

    Returns
    -------
    dist : ``(N,)`` float64 (or ``(S, N)`` if ``min_only=False``)
        Geodesic distance from the nearest source. Unreached voxels: ``+inf``.
    pred : ``(N,)`` int64 (or ``(S, N)``)
        Predecessor row index into ``voxels`` on the shortest path back to
        the source; ``-1`` for sources and unreached voxels (SciPy's
        convention). Feed to :func:`path` to reconstruct paths.
    """
    vox = _as_voxels(voxels)
    n = vox.shape[0]
    src = _as_sources(sources, n)

    if connectivity not in _CONNECTIVITIES:
        raise ValueError(f"connectivity must be one of {_CONNECTIVITIES}, got {connectivity}")
    if cost_mode not in _COST_MODES:
        raise ValueError(f"cost_mode must be one of {_COST_MODES}, got {cost_mode!r}")
    if index_kind not in _INDEX_KINDS:
        raise ValueError(f"index_kind must be one of {_INDEX_KINDS}, got {index_kind!r}")

    anisotropy = tuple(float(w) for w in anisotropy)
    if len(anisotropy) != 3 or not all(np.isfinite(w) and w > 0 for w in anisotropy):
        raise ValueError(f"anisotropy must be three finite positive floats, got {anisotropy}")
    free_eps = float(free_eps)
    if not (np.isfinite(free_eps) and free_eps > 0):
        raise ValueError(f"free_eps must be finite and > 0, got {free_eps}")

    if node_cost is not None:
        node_cost = _as_node_cost(node_cost, n)
    else:
        # Without per-voxel weights every mode degenerates to the pure
        # geometric step length (vertex: all-ones, additive: all-zeros).
        cost_mode = "geometric"

    if free_mask is not None:
        free_mask = np.ascontiguousarray(free_mask, dtype=bool)
        if free_mask.shape != (n,):
            raise ValueError(f"free_mask must have shape (N,) = ({n},), got {free_mask.shape}")

    dist, pred = _native.dijkstra_field(
        vox,
        src,
        node_cost if cost_mode != "geometric" else None,
        connectivity,
        anisotropy,
        cost_mode,
        free_mask,
        free_eps,
        bool(min_only),
        index_kind,
    )
    if not min_only:
        return dist.reshape(len(src), n), pred.reshape(len(src), n)
    return dist, pred


def path(
    voxels: npt.ArrayLike,
    pred: npt.ArrayLike,
    target: int,
    *,
    dist: Optional[npt.ArrayLike] = None,
) -> np.ndarray:
    """Reconstruct the source ``->`` target path by walking predecessors.

    Parameters
    ----------
    voxels
        The ``(N, 3)`` coordinate array the field was computed over.
    pred
        ``(N,)`` predecessor field from :func:`dijkstra_field`
        (``min_only=True`` shape; pass a single row of an ``(S, N)`` result).
    target
        Row index of the path endpoint.
    dist
        Optional distance field. If given, a ``target`` with infinite
        distance raises ``ValueError`` instead of silently returning the
        single-voxel path ``[target]`` (which is otherwise indistinguishable
        from ``target`` being a source).

    Returns
    -------
    ``(M, 3)`` int32 coordinates ordered from the source to ``target``
    (both inclusive).
    """
    vox = _as_voxels(voxels)
    n = vox.shape[0]
    pred = np.asarray(pred)
    if pred.shape != (n,):
        raise ValueError(
            f"pred must have shape (N,) = ({n},), got {pred.shape} "
            "(for min_only=False results, pass a single row)"
        )
    target = int(target)
    if not 0 <= target < n:
        raise ValueError(f"target index {target} out of range for {n} voxels")
    if dist is not None:
        dist = np.asarray(dist)
        if dist.shape != (n,):
            raise ValueError(f"dist must have shape (N,) = ({n},), got {dist.shape}")
        if not np.isfinite(dist[target]):
            raise ValueError(f"target {target} was not reached (dist is not finite)")

    rows = [target]
    node = target
    for _ in range(n):
        node = int(pred[node])
        if node == -1:
            break
        rows.append(node)
    else:
        raise ValueError("predecessor field contains a cycle — was it produced by dijkstra_field?")
    return vox[rows[::-1]]


def connected_components(
    voxels: npt.ArrayLike,
    *,
    connectivity: int = 26,
    index_kind: str = "hash",
) -> Tuple[int, np.ndarray]:
    """Connected components of the sparse voxel set (union-find).

    Two voxels are connected when their coordinates differ by one of the
    ``connectivity`` neighbour offsets. Labels are dense ``0..n_components-1``
    in order of first appearance by row, so output is deterministic.

    Returns ``(n_components, labels)`` with ``labels`` of shape ``(N,)``,
    int32.
    """
    vox = _as_voxels(voxels)
    if connectivity not in _CONNECTIVITIES:
        raise ValueError(f"connectivity must be one of {_CONNECTIVITIES}, got {connectivity}")
    if index_kind not in _INDEX_KINDS:
        raise ValueError(f"index_kind must be one of {_INDEX_KINDS}, got {index_kind!r}")
    return _native.connected_components(vox, connectivity, index_kind)


def index_of(
    voxels: npt.ArrayLike,
    coords: npt.ArrayLike,
    *,
    strict: bool = True,
    index_kind: str = "hash",
) -> Union[int, np.ndarray]:
    """Row indices in ``voxels`` for the given coordinates.

    Convenience for callers who hold coordinates rather than row indices
    (e.g. to build the ``sources`` argument of :func:`dijkstra_field`).

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates.
    coords
        A single ``(3,)`` coordinate or an ``(M, 3)`` array.
    strict
        If True (default), raise ``KeyError`` when any coordinate is not in
        ``voxels``; if False, return ``-1`` for missing coordinates.

    Returns
    -------
    An int for a single coordinate, else an ``(M,)`` int64 array.
    """
    vox = _as_voxels(voxels)
    if index_kind not in _INDEX_KINDS:
        raise ValueError(f"index_kind must be one of {_INDEX_KINDS}, got {index_kind!r}")
    q = np.asarray(coords)
    single = q.ndim == 1
    q = _as_voxels(np.atleast_2d(q))
    out = _native.index_of(vox, q, index_kind)
    if strict and out.size and out.min() < 0:
        missing = q[out < 0]
        raise KeyError(f"coordinates not present in voxels: {missing[:5].tolist()}")
    return int(out[0]) if single else out
