"""Dijkstra shortest paths over sparse 3D voxel sets.

A sparse analogue of `dijkstra3d <https://github.com/seung-lab/dijkstra3d>`_:
the same implicit-grid walk (neighbours generated by coordinate offset, no
adjacency list ever materialized), but the dense bbox-sized lookup array is
replaced by a sparse ``coordinate -> compact index`` map. All working memory
is ``O(N)`` in the number of voxels, independent of the bounding-box volume.

Voxels are given as an ``(N, 3)`` integer coordinate array; all per-voxel
inputs and outputs (``node_cost``, ``free_mask``, ``dist``, ``pred``,
``labels``) are 1-D arrays aligned with the rows of ``voxels``.

For repeated queries over the *same* voxel set, build a :class:`Graph`
once and call its methods — it reuses the spatial index that the free
functions rebuild on every call.
"""

from __future__ import annotations

from typing import Optional, Tuple, Union

import numpy as np
import numpy.typing as npt

from . import _native

__all__ = [
    "Graph",
    "dijkstra_field",
    "shortest_path",
    "shortest_path_to_set",
    "path",
    "connected_components",
    "label_adjacency",
    "exposed_faces",
    "factorize",
    "index_of",
    "__version__",
]

__version__ = "0.2.2"

_COST_MODES = ("vertex", "additive", "geometric")
_CONNECTIVITIES = (6, 18, 26)
_INDEX_KINDS = ("sorted", "hash")


def _as_voxels(voxels: npt.ArrayLike) -> np.ndarray:
    """Coerce to a C-contiguous (N, 3) int32 array, rejecting lossy casts."""
    arr = np.asarray(voxels)
    if arr.ndim != 2 or arr.shape[1] != 3:
        raise ValueError(f"voxels must have shape (N, 3), got {arr.shape}")
    if not np.issubdtype(arr.dtype, np.integer):
        raise ValueError(f"voxels must be an integer array, got dtype {arr.dtype}")
    if arr.dtype != np.int32:
        if arr.size and (arr.min() < np.iinfo(np.int32).min or arr.max() > np.iinfo(np.int32).max):
            raise ValueError("voxel coordinates exceed the int32 range")
        arr = arr.astype(np.int32)
    return np.ascontiguousarray(arr)


def _as_sources(sources: npt.ArrayLike, n: int) -> np.ndarray:
    arr = np.atleast_1d(np.asarray(sources))
    if arr.ndim != 1:
        raise ValueError(f"sources must be a 1-D array of row indices, got shape {arr.shape}")
    if arr.size and not np.issubdtype(arr.dtype, np.integer):
        raise ValueError(f"sources must be integer row indices into voxels, got dtype {arr.dtype}")
    arr = np.ascontiguousarray(arr, dtype=np.int64)
    if arr.size and (arr.min() < 0 or arr.max() >= n):
        bad = arr[(arr < 0) | (arr >= n)][0]
        raise ValueError(f"source index {bad} out of range for {n} voxels")
    return arr


def _as_node_cost(node_cost: npt.ArrayLike, n: int) -> np.ndarray:
    arr = np.ascontiguousarray(node_cost, dtype=np.float32)
    if arr.shape != (n,):
        raise ValueError(f"node_cost must have shape (N,) = ({n},), got {arr.shape}")
    if arr.size and (not np.all(np.isfinite(arr)) or arr.min() < 0):
        raise ValueError(
            "node_cost must be finite and non-negative "
            "(negative costs violate the Dijkstra invariant)"
        )
    return arr


def _as_int_field(name: str, values: npt.ArrayLike, n: int) -> np.ndarray:
    """Coerce a per-voxel integer field (``group``/``labels``) to (N,) int64.

    Integer dtypes only: these are compared for *equality*, which floats
    would make meaningless."""
    arr = np.asarray(values)
    if not np.issubdtype(arr.dtype, np.integer):
        raise ValueError(
            f"{name} must be an integer array (values are compared for equality), "
            f"got dtype {arr.dtype}"
        )
    arr = np.ascontiguousarray(arr, dtype=np.int64)
    if arr.shape != (n,):
        raise ValueError(f"{name} must have shape (N,) = ({n},), got {arr.shape}")
    return arr


def _field_args(
    n: int,
    sources: npt.ArrayLike,
    node_cost: Optional[npt.ArrayLike],
    connectivity: int,
    anisotropy: Tuple[float, float, float],
    cost_mode: str,
    free_mask: Optional[npt.ArrayLike],
    free_eps: float,
    min_only: bool,
    stop_mask: Optional[npt.ArrayLike],
    stop_count: int,
) -> tuple:
    """Validate the per-call arguments of a field run — everything except
    ``voxels``/``index_kind``, which are fixed by the :class:`Graph` handle.
    Returns the positional argument tuple for the native call."""
    src = _as_sources(sources, n)

    if connectivity not in _CONNECTIVITIES:
        raise ValueError(f"connectivity must be one of {_CONNECTIVITIES}, got {connectivity}")
    if cost_mode not in _COST_MODES:
        raise ValueError(f"cost_mode must be one of {_COST_MODES}, got {cost_mode!r}")

    anisotropy = tuple(float(w) for w in anisotropy)
    if len(anisotropy) != 3 or not all(np.isfinite(w) and w > 0 for w in anisotropy):
        raise ValueError(f"anisotropy must be three finite positive floats, got {anisotropy}")
    free_eps = float(free_eps)
    if not (np.isfinite(free_eps) and free_eps > 0):
        raise ValueError(f"free_eps must be finite and > 0, got {free_eps}")
    stop_count = int(stop_count)
    if stop_count < 0:
        raise ValueError(f"stop_count must be >= 0, got {stop_count}")

    if node_cost is not None:
        node_cost = _as_node_cost(node_cost, n)
    else:
        # Without per-voxel weights every mode degenerates to the pure
        # geometric step length (vertex: all-ones, additive: all-zeros).
        cost_mode = "geometric"

    if free_mask is not None:
        free_mask = np.ascontiguousarray(free_mask, dtype=bool)
        if free_mask.shape != (n,):
            raise ValueError(f"free_mask must have shape (N,) = ({n},), got {free_mask.shape}")
    if stop_mask is not None:
        stop_mask = np.ascontiguousarray(stop_mask, dtype=bool)
        if stop_mask.shape != (n,):
            raise ValueError(f"stop_mask must have shape (N,) = ({n},), got {stop_mask.shape}")

    return (
        src,
        node_cost if cost_mode != "geometric" else None,
        connectivity,
        anisotropy,
        cost_mode,
        free_mask,
        free_eps,
        bool(min_only),
        stop_mask,
        stop_count,
    )


class Graph:
    """Reusable handle: the spatial index over a fixed voxel set, built once.

    Every free function in this module rebuilds the ``coordinate -> row``
    spatial index — the one ``O(N)`` setup cost — on each call. ``Graph``
    hoists that build into the constructor, so repeated queries over the
    *same* voxel set (e.g. several distance fields plus many
    :meth:`shortest_path_to_set` grafts per skeleton component) pay it once.

    Only ``voxels`` and ``index_kind`` are fixed by the handle. Everything
    else — ``connectivity``, ``anisotropy``, ``cost_mode``, ``node_cost``,
    masks — remains a per-method argument, so one handle serves queries
    with different cost models. Results are identical to the corresponding
    free functions: only *where* the index is built moves.

    The handle keeps its own copy of the coordinates and is read-only after
    construction.

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates, as in :func:`dijkstra_field`.
        Duplicate coordinates are rejected here, at construction.
    index_kind
        Spatial-index backend, ``"hash"`` (default) or ``"sorted"``, fixed
        for the lifetime of the handle; see :func:`dijkstra_field`.
    """

    def __init__(self, voxels: npt.ArrayLike, *, index_kind: str = "hash"):
        vox = _as_voxels(voxels)
        if index_kind not in _INDEX_KINDS:
            raise ValueError(f"index_kind must be one of {_INDEX_KINDS}, got {index_kind!r}")
        self._voxels = vox
        self._graph = _native.Graph(vox, index_kind)

    @property
    def n(self) -> int:
        """Number of voxels."""
        return int(self._voxels.shape[0])

    @property
    def voxels(self) -> np.ndarray:
        """The ``(N, 3)`` int32 coordinate array (read-only view)."""
        view = self._voxels.view()
        view.flags.writeable = False
        return view

    @property
    def index_kind(self) -> str:
        """Spatial-index backend fixed at construction."""
        return self._graph.index_kind

    def __repr__(self) -> str:
        return f"Graph(n={self.n}, index_kind={self.index_kind!r})"

    def _field(
        self,
        sources: npt.ArrayLike,
        *,
        node_cost: Optional[npt.ArrayLike],
        connectivity: int,
        anisotropy: Tuple[float, float, float],
        cost_mode: str,
        free_mask: Optional[npt.ArrayLike],
        free_eps: float,
        min_only: bool,
        stop_mask: Optional[npt.ArrayLike],
        stop_count: int,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Validated core call, reusing the handle's index. Returns
        ``(dist, pred, hits)`` where ``hits`` holds the first-settled
        ``stop_mask`` row per Dijkstra run (``-1`` if none): shape ``(1,)``
        for ``min_only=True``, else ``(S,)``."""
        args = _field_args(
            self.n,
            sources,
            node_cost,
            connectivity,
            anisotropy,
            cost_mode,
            free_mask,
            free_eps,
            min_only,
            stop_mask,
            stop_count,
        )
        dist, pred, hits = self._graph.dijkstra_field(*args)
        if not min_only:
            src = args[0]
            return dist.reshape(len(src), self.n), pred.reshape(len(src), self.n), hits
        return dist, pred, hits

    def dijkstra_field(
        self,
        sources: npt.ArrayLike,
        *,
        node_cost: Optional[npt.ArrayLike] = None,
        connectivity: int = 26,
        anisotropy: Tuple[float, float, float] = (1.0, 1.0, 1.0),
        cost_mode: str = "vertex",
        free_mask: Optional[npt.ArrayLike] = None,
        free_eps: float = 1e-6,
        min_only: bool = True,
        stop_mask: Optional[npt.ArrayLike] = None,
        stop_count: int = 1,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Multi-source Dijkstra field over the handle's voxels.

        Identical to the free :func:`dijkstra_field` (see there for the
        full parameter and return documentation), with ``voxels`` and
        ``index_kind`` fixed by the handle — the spatial index is reused,
        not rebuilt.
        """
        dist, pred, _ = self._field(
            sources,
            node_cost=node_cost,
            connectivity=connectivity,
            anisotropy=anisotropy,
            cost_mode=cost_mode,
            free_mask=free_mask,
            free_eps=free_eps,
            min_only=min_only,
            stop_mask=stop_mask,
            stop_count=stop_count,
        )
        return dist, pred

    def shortest_path_to_set(
        self,
        source: int,
        stop_mask: npt.ArrayLike,
        *,
        node_cost: Optional[npt.ArrayLike] = None,
        connectivity: int = 26,
        anisotropy: Tuple[float, float, float] = (1.0, 1.0, 1.0),
        cost_mode: str = "vertex",
        free_mask: Optional[npt.ArrayLike] = None,
        free_eps: float = 1e-6,
    ) -> Tuple[np.ndarray, int, float]:
        """Shortest path from ``source`` to the nearest ``stop_mask`` voxel.

        Identical to the free :func:`shortest_path_to_set`, with ``voxels``
        and ``index_kind`` fixed by the handle. This is the grafting
        primitive that benefits most from the handle: each call skips the
        ``O(N)`` index rebuild, leaving only the (early-terminating) search.
        """
        stop_mask = np.ascontiguousarray(stop_mask, dtype=bool)
        dist, pred, hits = self._field(
            source,
            node_cost=node_cost,
            connectivity=connectivity,
            anisotropy=anisotropy,
            cost_mode=cost_mode,
            free_mask=free_mask,
            free_eps=free_eps,
            min_only=True,
            stop_mask=stop_mask,
            stop_count=1,
        )
        hit = int(hits[0])
        if hit < 0:
            return np.empty((0, 3), dtype=np.int32), -1, float("inf")
        return path(self._voxels, pred, hit), hit, float(dist[hit])

    def shortest_path(
        self,
        source: int,
        target: int,
        *,
        node_cost: Optional[npt.ArrayLike] = None,
        connectivity: int = 26,
        anisotropy: Tuple[float, float, float] = (1.0, 1.0, 1.0),
        cost_mode: str = "vertex",
        free_mask: Optional[npt.ArrayLike] = None,
        free_eps: float = 1e-6,
    ) -> Tuple[np.ndarray, float]:
        """Single ``source`` → ``target`` shortest path.

        Identical to the free :func:`shortest_path`, with ``voxels`` and
        ``index_kind`` fixed by the handle.
        """
        n = self.n
        target = int(target)
        if not 0 <= target < n:
            raise ValueError(f"target index {target} out of range for {n} voxels")
        stop_mask = np.zeros(n, dtype=bool)
        stop_mask[target] = True
        coords, _hit, cost = self.shortest_path_to_set(
            source,
            stop_mask,
            node_cost=node_cost,
            connectivity=connectivity,
            anisotropy=anisotropy,
            cost_mode=cost_mode,
            free_mask=free_mask,
            free_eps=free_eps,
        )
        return coords, cost

    def connected_components(
        self,
        *,
        group: Optional[npt.ArrayLike] = None,
        connectivity: int = 26,
    ) -> Tuple[int, np.ndarray]:
        """Connected components of the handle's voxel set.

        Identical to the free :func:`connected_components`, with ``voxels``
        and ``index_kind`` fixed by the handle.
        """
        if connectivity not in _CONNECTIVITIES:
            raise ValueError(f"connectivity must be one of {_CONNECTIVITIES}, got {connectivity}")
        if group is not None:
            group = _as_int_field("group", group, self.n)
        return self._graph.connected_components(connectivity, group)

    def label_adjacency(
        self,
        labels: npt.ArrayLike,
        *,
        connectivity: int = 26,
    ) -> np.ndarray:
        """Pairs of distinct labels that touch, over the handle's voxels.

        Identical to the free :func:`label_adjacency`, with ``voxels`` and
        ``index_kind`` fixed by the handle.
        """
        if connectivity not in _CONNECTIVITIES:
            raise ValueError(f"connectivity must be one of {_CONNECTIVITIES}, got {connectivity}")
        labels = _as_int_field("labels", labels, self.n)
        return self._graph.label_adjacency(labels, connectivity).reshape(-1, 2)

    def exposed_faces(self) -> np.ndarray:
        """Per-voxel 6-bit mask of absent face-neighbours, over the handle's
        voxels.

        Identical result to the free :func:`exposed_faces`, but note the
        memory trade-off is the opposite one: this reuses (and keeps) the
        handle's index, so it does *not* free the index within the call. The
        free function is the one whose whole point is a transient index — use
        it, not a throwaway handle, when the surface pass is all you need.

        This is the one query where the two backends differ markedly. A
        ``"sorted"`` handle answers it by merging its key array against
        itself, with no lookups at all; a ``"hash"`` one has to probe, which
        costs several times more. Neither allocates. If a handle exists mainly
        to serve surface passes, build it with ``index_kind="sorted"``.
        """
        return self._graph.exposed_faces()

    def index_of(self, coords: npt.ArrayLike, *, strict: bool = True) -> Union[int, np.ndarray]:
        """Row indices of the given coordinates in the handle's voxels.

        Identical to the free :func:`index_of`, with ``voxels`` and
        ``index_kind`` fixed by the handle.
        """
        q = np.asarray(coords)
        single = q.ndim == 1
        q = _as_voxels(np.atleast_2d(q))
        out = self._graph.index_of(q)
        if strict and out.size and out.min() < 0:
            missing = q[out < 0]
            raise KeyError(f"coordinates not present in voxels: {missing[:5].tolist()}")
        return int(out[0]) if single else out

    def path(
        self,
        pred: npt.ArrayLike,
        target: int,
        *,
        dist: Optional[npt.ArrayLike] = None,
    ) -> np.ndarray:
        """Convenience for :func:`path` over the handle's voxels (a pure
        predecessor walk — it never touches the spatial index)."""
        return path(self._voxels, pred, target, dist=dist)


def dijkstra_field(
    voxels: npt.ArrayLike,
    sources: npt.ArrayLike,
    *,
    node_cost: Optional[npt.ArrayLike] = None,
    connectivity: int = 26,
    anisotropy: Tuple[float, float, float] = (1.0, 1.0, 1.0),
    cost_mode: str = "vertex",
    free_mask: Optional[npt.ArrayLike] = None,
    free_eps: float = 1e-6,
    min_only: bool = True,
    stop_mask: Optional[npt.ArrayLike] = None,
    stop_count: int = 1,
    index_kind: str = "hash",
) -> Tuple[np.ndarray, np.ndarray]:
    """Multi-source Dijkstra distance + predecessor field over sparse voxels.

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates (unsorted is fine, duplicates
        are rejected). Any integer dtype in int32 range.
    sources
        Row indices into ``voxels`` to start from (scalar or 1-D array).
        Use :func:`index_of` if you hold coordinates instead. May be empty,
        in which case every voxel is unreached.
    node_cost
        Optional ``(N,)`` per-voxel weight, ``float32`` (other dtypes are
        converted). Must be finite and non-negative. When ``None``, every
        edge costs just its geometric step length regardless of
        ``cost_mode``.
    connectivity
        6, 18 or 26 (face / face+edge / face+edge+corner neighbours).
    anisotropy
        Physical voxel spacing ``(wx, wy, wz)``. Step lengths are
        ``sqrt((dx*wx)^2 + (dy*wy)^2 + (dz*wz)^2)``, matching ``dijkstra3d``.
    cost_mode
        - ``"vertex"`` (default): ``cost = node_cost[nbr] * step_length`` —
          ``dijkstra3d``-compatible vertex weighting.
        - ``"additive"``: ``cost = step_length + node_cost[nbr]`` — geometric
          length plus a per-voxel penalty.
        - ``"geometric"``: ``cost = step_length`` — anisotropic geodesic
          distance; ``node_cost`` is ignored.
    free_mask
        Optional ``(N,)`` bool mask. Edges *into* masked voxels cost
        ``free_eps`` in total, so later paths can ride an already-selected
        node set for ~free before diverging (incremental path grafting).
    free_eps
        Strictly positive cost of edges into ``free_mask`` voxels.
    min_only
        With multiple sources: if True (default) return one field with the
        distance to the *nearest* source; if False run one Dijkstra per
        source and return ``(S, N)`` arrays (rows ordered like ``sources``),
        mirroring :func:`scipy.sparse.csgraph.dijkstra`.
    stop_mask
        Optional ``(N,)`` bool mask of stop nodes ("anchors"/"targets"). The
        search terminates early once ``stop_count`` masked voxels have been
        *settled*, returning the partial field: everything the search
        touched is exact (identical to the full field), everything beyond
        keeps ``dist = +inf``, ``pred = -1``. This is something SciPy's
        ``limit`` cutoff cannot express — see :func:`shortest_path_to_set`
        and :func:`shortest_path` for the ergonomic entry points. With
        ``min_only=False``, each per-source run stops independently.
    stop_count
        Stop after this many ``stop_mask`` voxels settle (default 1 — stop
        at the nearest). ``0`` disables early termination (full field).
    index_kind
        Spatial-index backend, ``"hash"`` (hash map, default — fastest in
        our benchmarks) or ``"sorted"`` (binary search over sorted keys,
        slightly lower memory). Identical results; performance knob only.

    Returns
    -------
    dist : ``(N,)`` float64 (or ``(S, N)`` if ``min_only=False``)
        Geodesic distance from the nearest source. Unreached voxels: ``+inf``.
    pred : ``(N,)`` int64 (or ``(S, N)``)
        Predecessor row index into ``voxels`` on the shortest path back to
        the source; ``-1`` for sources and unreached voxels (SciPy's
        convention). Feed to :func:`path` to reconstruct paths.

    See Also
    --------
    Graph : builds the spatial index once for repeated queries over the
        same voxels — identical results without the per-call rebuild.
    """
    return Graph(voxels, index_kind=index_kind).dijkstra_field(
        sources,
        node_cost=node_cost,
        connectivity=connectivity,
        anisotropy=anisotropy,
        cost_mode=cost_mode,
        free_mask=free_mask,
        free_eps=free_eps,
        min_only=min_only,
        stop_mask=stop_mask,
        stop_count=stop_count,
    )


def shortest_path_to_set(
    voxels: npt.ArrayLike,
    source: int,
    stop_mask: npt.ArrayLike,
    *,
    node_cost: Optional[npt.ArrayLike] = None,
    connectivity: int = 26,
    anisotropy: Tuple[float, float, float] = (1.0, 1.0, 1.0),
    cost_mode: str = "vertex",
    free_mask: Optional[npt.ArrayLike] = None,
    free_eps: float = 1e-6,
    index_kind: str = "hash",
) -> Tuple[np.ndarray, int, float]:
    """Shortest path from ``source`` to the *nearest* voxel in ``stop_mask``.

    The search terminates the instant the first anchor settles, so each call
    explores only the catchment ball around ``source`` out to the nearest
    anchor — not the full voxel set. This is the primitive for incremental
    tree construction (grafting): query against a growing anchor set, add
    the returned path to the mask, repeat — each graft gets cheaper as the
    anchors densify.

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates.
    source
        Row index to start from. If ``stop_mask[source]`` is set, the query
        trivially returns the single-voxel path (exclude sources from the
        mask if self-hits are unwanted).
    stop_mask
        ``(N,)`` bool anchor set.
    node_cost, connectivity, anisotropy, cost_mode, free_mask, free_eps, index_kind
        As in :func:`dijkstra_field`. Note the cost model is directed:
        with ``cost_mode="vertex"`` the source→anchor path optimises
        ``node_cost`` of *entered* voxels, which differs from the
        anchor→source direction. ``geometric``/``additive`` costs are
        direction-symmetric.

    Returns
    -------
    path : ``(M, 3)`` int32
        Coordinates from ``source`` to the hit anchor (both inclusive);
        empty ``(0, 3)`` if no anchor is reachable.
    hit : int
        Row index of the anchor reached, or ``-1`` if none is reachable.
    cost : float
        Path cost ``dist[hit]``; ``+inf`` if none is reachable.
    """
    return Graph(voxels, index_kind=index_kind).shortest_path_to_set(
        source,
        stop_mask,
        node_cost=node_cost,
        connectivity=connectivity,
        anisotropy=anisotropy,
        cost_mode=cost_mode,
        free_mask=free_mask,
        free_eps=free_eps,
    )


def shortest_path(
    voxels: npt.ArrayLike,
    source: int,
    target: int,
    *,
    node_cost: Optional[npt.ArrayLike] = None,
    connectivity: int = 26,
    anisotropy: Tuple[float, float, float] = (1.0, 1.0, 1.0),
    cost_mode: str = "vertex",
    free_mask: Optional[npt.ArrayLike] = None,
    free_eps: float = 1e-6,
    index_kind: str = "hash",
) -> Tuple[np.ndarray, float]:
    """Single ``source`` → ``target`` shortest path, terminating the search
    the instant ``target`` settles (no full field is computed).

    Returns ``(path, cost)``: ``(M, 3)`` int32 coordinates from ``source``
    to ``target`` and the path cost. If ``target`` is unreachable, returns
    an empty ``(0, 3)`` array and ``+inf`` (no exception). Other parameters
    as in :func:`dijkstra_field`.
    """
    return Graph(voxels, index_kind=index_kind).shortest_path(
        source,
        target,
        node_cost=node_cost,
        connectivity=connectivity,
        anisotropy=anisotropy,
        cost_mode=cost_mode,
        free_mask=free_mask,
        free_eps=free_eps,
    )


def path(
    voxels: npt.ArrayLike,
    pred: npt.ArrayLike,
    target: int,
    *,
    dist: Optional[npt.ArrayLike] = None,
) -> np.ndarray:
    """Reconstruct the source ``->`` target path by walking predecessors.

    Parameters
    ----------
    voxels
        The ``(N, 3)`` coordinate array the field was computed over.
    pred
        ``(N,)`` predecessor field from :func:`dijkstra_field`
        (``min_only=True`` shape; pass a single row of an ``(S, N)`` result).
    target
        Row index of the path endpoint.
    dist
        Optional distance field. If given, a ``target`` with infinite
        distance raises ``ValueError`` instead of silently returning the
        single-voxel path ``[target]`` (which is otherwise indistinguishable
        from ``target`` being a source).

    Returns
    -------
    ``(M, 3)`` int32 coordinates ordered from the source to ``target``
    (both inclusive).
    """
    vox = _as_voxels(voxels)
    n = vox.shape[0]
    pred = np.asarray(pred)
    if pred.shape != (n,):
        raise ValueError(
            f"pred must have shape (N,) = ({n},), got {pred.shape} "
            "(for min_only=False results, pass a single row)"
        )
    target = int(target)
    if not 0 <= target < n:
        raise ValueError(f"target index {target} out of range for {n} voxels")
    if dist is not None:
        dist = np.asarray(dist)
        if dist.shape != (n,):
            raise ValueError(f"dist must have shape (N,) = ({n},), got {dist.shape}")
        if not np.isfinite(dist[target]):
            raise ValueError(f"target {target} was not reached (dist is not finite)")

    rows = [target]
    node = target
    for _ in range(n):
        node = int(pred[node])
        if node == -1:
            break
        rows.append(node)
    else:
        raise ValueError("predecessor field contains a cycle — was it produced by dijkstra_field?")
    return vox[rows[::-1]]


def connected_components(
    voxels: npt.ArrayLike,
    *,
    group: Optional[npt.ArrayLike] = None,
    connectivity: int = 26,
    index_kind: str = "hash",
) -> Tuple[int, np.ndarray]:
    """Connected components of the sparse voxel set (union-find).

    Two voxels are connected when (a) their coordinates differ by one of the
    ``connectivity`` neighbour offsets and (b) ``group`` is ``None`` or their
    ``group`` values are equal. Labels are dense ``0..n_components-1`` in
    order of first appearance by row, so output is deterministic.

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates.
    group
        Optional ``(N,)`` integer field. When given, only neighbours with
        *equal* group values are connected — i.e. the components of the
        sub-graph induced by each group value (e.g. the "rings" of a
        geodesic level set, ``group = floor(dist / step)``). Grouping only
        *constrains* unions: the same value occurring in two spatially
        separate places still yields two components, and a voxel whose group
        differs from all its neighbours' becomes a singleton. Integer dtypes
        only — the values are compared for equality.
    connectivity
        6, 18 or 26.
    index_kind
        Spatial-index backend; see :func:`dijkstra_field`.

    Returns
    -------
    ``(n_components, labels)`` with ``labels`` of shape ``(N,)``, int32.
    """
    return Graph(voxels, index_kind=index_kind).connected_components(
        group=group, connectivity=connectivity
    )


def label_adjacency(
    voxels: npt.ArrayLike,
    labels: npt.ArrayLike,
    *,
    connectivity: int = 26,
    index_kind: str = "hash",
) -> np.ndarray:
    """Which pairs of distinct labels touch, without building an edge list.

    For every pair of ``connectivity``-adjacent voxels ``u, v`` with
    ``labels[u] != labels[v]``, the pair is emitted once. This contracts the
    voxel graph onto the label graph — the quotient/adjacency graph of a
    labelling such as :func:`connected_components` output — in one pass over
    the implicit grid, deduplicating as it goes. The intermediate adjacency
    count never materializes.

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates.
    labels
        ``(N,)`` integer label per voxel. Need *not* be dense or
        non-negative — any integer labelling works.
    connectivity
        6, 18 or 26.
    index_kind
        Spatial-index backend; see :func:`dijkstra_field`.

    Returns
    -------
    ``(K, 2)`` int64 array of distinct pairs ``(lo, hi)`` with ``lo < hi``,
    lexicographically sorted (deterministic). Empty input or a single label
    gives a well-formed ``(0, 2)`` array.
    """
    return Graph(voxels, index_kind=index_kind).label_adjacency(labels, connectivity=connectivity)


def exposed_faces(
    voxels: npt.ArrayLike,
    *,
    index_kind: str = "hash",
) -> np.ndarray:
    """Per voxel, a 6-bit mask of which face-neighbours are absent from the set.

    This is the surface-extraction probe: a face is *exposed* exactly when the
    voxel one step across it is not itself a voxel. For each row it answers all
    six face directions at once, as one bit each, so the caller can split the
    result into directional sets (``voxels_left`` / ``voxels_right`` / …) with
    cheap boolean gathers rather than six coordinate probes.

    Unlike the other free functions in this module, this one does **not** route
    through a :class:`Graph`, and builds no spatial index at all: it sorts one
    packed 16-byte key per voxel, sweeps the three positive face offsets across
    it as three linear merges, and frees that array — all inside the native
    call, before the output array is even handed back. Nothing persists
    (:meth:`Graph.exposed_faces` reuses a persistent index and so gives up the
    memory win); the surface pass's own footprint never stacks under a later
    peak.

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates (any integer dtype in int32
        range). Duplicate coordinates are rejected, as by :class:`Graph`.
    index_kind
        Accepted for signature parity with the other free functions. The
        surface sweep builds its own sorted key array — cheaper in both time
        and memory than either backend — so this changes neither the result
        nor the cost (there is no :class:`Graph` handle to build here).

    Returns
    -------
    ``(N,)`` uint8 mask, row-aligned with ``voxels``. Bit ``k`` of ``mask[i]``
    is set iff ``voxels[i] + FACE_OFFSET[k]`` is **not** in ``voxels``, where
    the face offsets are, in bit order::

        bit 0: (+1, 0, 0)   bit 1: (-1, 0, 0)
        bit 2: (0, +1, 0)   bit 3: (0, -1, 0)
        bit 4: (0, 0, +1)   bit 5: (0, 0, -1)

    A fully interior voxel yields ``0``; a lone voxel yields ``0b111111``
    (``63``). To recover the voxels with (say) their ``-x`` face exposed:
    ``voxels[(mask & (1 << 1)) != 0]``.

    Notes
    -----
    "Exposed face" is inherently a 6-connectivity notion, so there is no
    ``connectivity`` parameter.

    Only three offsets are ever probed: an adjacency found from the ``+axis``
    side also clears the far voxel's ``-axis`` bit. Combined with the merge
    sweep this makes the pass linear in ``N`` after the sort, and the sort
    itself is a single scan when ``voxels`` already arrives in lexicographic
    order (what ``np.argwhere`` / ``np.unique(..., axis=0)`` hand over).
    """
    vox = _as_voxels(voxels)
    if index_kind not in _INDEX_KINDS:
        raise ValueError(f"index_kind must be one of {_INDEX_KINDS}, got {index_kind!r}")
    # Deliberately *not* Graph(...).exposed_faces(): the native free function
    # drops its key array inside the call, which the persistent handle cannot.
    return _native.exposed_faces(vox, index_kind)


def factorize(
    voxels: npt.ArrayLike,
    *,
    return_index: bool = False,
    index_kind: str = "hash",
) -> Union[Tuple[int, np.ndarray], Tuple[int, np.ndarray, np.ndarray]]:
    """Dense labels for coordinates by exact equality; duplicates collapse.

    The sparse analogue of ``np.unique(coords, axis=0, return_inverse=True)``,
    computed as a single hash pass rather than a sort. Each row is assigned a
    label, equal exactly when the coordinates are equal, so an array that is
    mostly repeats (the four-corners-per-quad a mesher emits, the coarse cell
    each fine voxel downsamples into) collapses to its distinct set with an
    inverse mapping back to every row.

    Unlike :class:`Graph`, :func:`index_of` and :func:`connected_components` —
    which **reject** duplicate coordinates — this is *built for* duplicated
    input: duplicates are the point, not an error. And unlike
    :func:`connected_components`, which also returns ``(n, labels)`` but groups
    by spatial *adjacency*, ``factorize`` groups by exact coordinate
    *equality*; a caller holding already-unique coordinates does not need it.

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer coordinates (any integer dtype in int32 range),
        duplicates allowed. Negative coordinates work — the coordinates are
        hashed as-is, so no non-negative shift is required.
    return_index
        If True, also return ``reps``: the row index of the first occurrence
        of each label, so ``voxels[reps]`` is the deduplicated coordinate set,
        aligned with the labels.
    index_kind
        Accepted for signature parity with the other free functions. The
        factorize is always a single hash pass, so this does not change the
        result (there is no ``Graph`` handle to build here).

    Returns
    -------
    n_labels : int
        Number of distinct coordinates.
    labels : ``(N,)`` int64
        Dense label per row, ``0 .. n_labels-1``, assigned in order of first
        appearance by row. ``labels[i] == labels[j]`` iff ``voxels[i]`` and
        ``voxels[j]`` are the same coordinate.
    reps : ``(n_labels,)`` int64, *only if* ``return_index``
        ``reps[k]`` is the first row with label ``k`` (strictly increasing, so
        ``voxels[reps]`` lists the distinct coordinates in first-appearance
        order). ``voxels[reps][labels]`` reconstructs ``voxels``.

    Notes
    -----
    Exact integer equality only — no tolerance or rounding. ``N == 0`` returns
    ``(0, empty)`` (or ``(0, empty, empty)`` with ``return_index``).
    """
    vox = _as_voxels(voxels)
    if index_kind not in _INDEX_KINDS:
        raise ValueError(f"index_kind must be one of {_INDEX_KINDS}, got {index_kind!r}")
    n_labels, labels, reps = _native.factorize(vox, bool(return_index), index_kind)
    if return_index:
        return n_labels, labels, reps
    return n_labels, labels


def index_of(
    voxels: npt.ArrayLike,
    coords: npt.ArrayLike,
    *,
    strict: bool = True,
    index_kind: str = "hash",
) -> Union[int, np.ndarray]:
    """Row indices in ``voxels`` for the given coordinates.

    Convenience for callers who hold coordinates rather than row indices
    (e.g. to build the ``sources`` argument of :func:`dijkstra_field`).

    Parameters
    ----------
    voxels
        ``(N, 3)`` integer voxel coordinates.
    coords
        A single ``(3,)`` coordinate or an ``(M, 3)`` array.
    strict
        If True (default), raise ``KeyError`` when any coordinate is not in
        ``voxels``; if False, return ``-1`` for missing coordinates.

    Returns
    -------
    An int for a single coordinate, else an ``(M,)`` int64 array.
    """
    return Graph(voxels, index_kind=index_kind).index_of(coords, strict=strict)
