//! Neighbour offsets for the implicit grid graph.
//!
//! A voxel's neighbours are generated by coordinate offset — no adjacency
//! list is ever materialized. Each offset carries a precomputed step-length
//! multiplier derived from the anisotropic voxel spacing, matching
//! `dijkstra3d` exactly:
//!
//! - axis moves: `wx`, `wy`, `wz`
//! - face diagonals (18-conn): `sqrt(wa^2 + wb^2)`
//! - corner diagonals (26-conn): `sqrt(wa^2 + wb^2 + wc^2)`

/// `(dx, dy, dz, step_length)` for every neighbour offset of the requested
/// connectivity. Order is fixed (lexicographic scan) so results are
/// deterministic across runs and platforms.
pub fn build_offsets(connectivity: u8, anisotropy: [f64; 3]) -> Vec<(i32, i32, i32, f64)> {
    let max_manhattan = match connectivity {
        6 => 1,
        18 => 2,
        26 => 3,
        _ => panic!("connectivity must be 6, 18 or 26"),
    };
    let mut out = Vec::with_capacity(connectivity as usize);
    for dx in -1..=1i32 {
        for dy in -1..=1i32 {
            for dz in -1..=1i32 {
                let manhattan = dx.abs() + dy.abs() + dz.abs();
                if manhattan == 0 || manhattan > max_manhattan {
                    continue;
                }
                let len = ((dx as f64 * anisotropy[0]).powi(2)
                    + (dy as f64 * anisotropy[1]).powi(2)
                    + (dz as f64 * anisotropy[2]).powi(2))
                .sqrt();
                out.push((dx, dy, dz, len));
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn offset_counts() {
        assert_eq!(build_offsets(6, [1.0; 3]).len(), 6);
        assert_eq!(build_offsets(18, [1.0; 3]).len(), 18);
        assert_eq!(build_offsets(26, [1.0; 3]).len(), 26);
    }

    #[test]
    fn anisotropic_lengths() {
        let offs = build_offsets(26, [2.0, 3.0, 5.0]);
        for (dx, dy, dz, len) in offs {
            let expect =
                ((dx as f64 * 2.0).powi(2) + (dy as f64 * 3.0).powi(2) + (dz as f64 * 5.0).powi(2))
                    .sqrt();
            assert!((len - expect).abs() < 1e-12);
            // axis moves reduce to the bare spacing
            if dx.abs() + dy.abs() + dz.abs() == 1 {
                let w = if dx != 0 {
                    2.0
                } else if dy != 0 {
                    3.0
                } else {
                    5.0
                };
                assert!((len - w).abs() < 1e-12);
            }
        }
    }
}
